device:
  layer: rpi4
  hostname: ${HOSTNAME}
  user1: assistant
  user1pass: ${PASSWORD}

wifi:
  ssid: wifiwifiwifiwifi-iot
  password: ${WIFI_PASSWORD}

image:
  name: voice-assistant
  layer: image-rpios
  boot_part_size: 512M
  root_part_size: 2G

ssh:
  pubkey_only: n

layer:
  custom: voice-assistant
